### ISSUE TITLE
consider using git tags in sync with crates.io for distro packaging

### ISSUE THREAD

**Issue by anthraxx** [Ben-Lichtman/ropr#1]
Hi!

I would like to kindly ask if you could start using git tags in sync with crates.io. This would allow easier mapping of to specific commit to a crates release. Furthermore ans specifically it would allow distro packagers that package out of source repos to create a distro repository package.

Please consider also pushing the 0.2.12 git tag :cat: 

thank you very much

**Comment by anthraxx** [comment]
@Ben-Lichtman https://archlinux.org/packages/community/x86_64/ropr/

**Comment by Ben-Lichtman** [comment]
Awesome! Thanks :)
