### ISSUE TITLE
Printing "Found X gadgets" in the middle of the output

### ISSUE THREAD

**Issue by Acebond** [Ben-Lichtman/ropr#18]
The tool seems to print the "Found X gadgets" in the middle of the output sometimes. This seems like its supposed to be printed at the end. 

![image](https://github.com/user-attachments/assets/d89ed2ca-d711-4e93-b82f-1b876fe1529e)

**Comment by Ben-Lichtman** [comment]
Oops yeah, looks like I need to flush stdout before I call that print.

if it helps in the mean time, that "found x gadgets" message is only being printed to stderr, so you can easily separate it by piping stderr elsewhere.

**Comment by Ben-Lichtman** [comment]
This should be fixed by the latest version. Please test it and let me and reopen this issue if you still encounter it.
