### ISSUE TITLE
Piping output into head panics

### ISSUE THREAD

**Issue by 0xricksanchez** [Ben-Lichtman/ropr#8]
It's me again :D! Just noticed a weird behavior that's just a small UX thing:

![image](https://user-images.githubusercontent.com/17012133/155324433-fe0e138f-c68d-45f8-96ba-76cef5d7a95a.png)

Piping into tail, sort, or even vim works just fine, but piping directly into head does not. Not sure where the inconsistency comes from here, but I figured I'd let you know.

Cheers

**Comment by Ben-Lichtman** [comment]
Hi, this is because head may close stdin before it finishes reading everything. This should not affect most uses and I was already aware of this issue, but I should probably handle the case anyway.

**Comment by Ben-Lichtman** [comment]
fixed in 0.2.21

**Comment by Ben-Lichtman** [comment]
btw you can add -c true to the arguments to force ANSI colours to pass through to head / other pipes
